services:
  - type: web
    name: exaroton-telegram-bot
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: EXAROTON_API_TOKEN
        sync: false
      - key: EXAROTON_SERVER_ID
        value: IwjrQumZ1ZdDDSRX
      - key: ALLOWED_TELEGRAM_IDS
        value: 1534687734
      - key: PUBLIC_URL
        sync: false
      - key: WEBHOOK_PATH
        value: /telegram/webhook
      - key: TELEGRAM_WEBHOOK_SECRET
        sync: false
